version: '1.0.4.{build}'
image: Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmd: nuget restore

build:
  project: connect-or-cut.sln

before_test:
  - ps: cp coc.ps1 $env:PLATFORM\$env:CONFIGURATION
  - ps: cp testsuite.ps1 $env:PLATFORM\$env:CONFIGURATION

test_script:
  - ps: testsuite.ps1