version: '1.0.4.{build}'
image: Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmd: nuget restore

build:
  project: connect-or-cut.sln

before_test:
  - ps: if ($env:PLATFORM -eq "x64") { cp coc.ps1 $env:PLATFORM\$env:CONFIGURATION }
  - ps: if ($env:PLATFORM -eq "x64") { cp testsuite.ps1 $env:PLATFORM\$env:CONFIGURATION }

test_script:
  - ps: if ($env:PLATFORM -eq "x64") { & $env:PLATFORM\$env:CONFIGURATION\testsuite.ps1 -Verbose }

after_build:
  - ps: |
      if ($env:CONFIGURATION -eq "Release") {
        if ($env:PLATFORM -eq "x64") {
          $folder = "$env:APPVEYOR_BUILD_FOLDER\x64\Release"
          $bit = "64"
        } else {
          $folder = "$env:APPVEYOR_BUILD_FOLDER\Release"
          $bit = "32"
        }
        7z a "connect-or-cut-$env:APPVEYOR_BUILD_VERSION-$bit.zip" README.md LICENSE coc.ps1 testsuite.ps1 "$folder\*.dll" "$folder\*.exe"
        Push-AppveyorArtifact "connect-or-cut-$env:APPVEYOR_BUILD_VERSION-$bit.zip"
      }

deploy:
  description: 'connect-or-cut v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: 2J7opUzk3HlidHQBGIm76vtRaCwvuobgN/KxvDv6Ak/ksx14KKH5FKInwDUcTPRQ
  draft: true
  prerelease: true
  on:
    branch: master
    configuration: Release
    platform: x64
    APPVEYOR_REPO_TAG: true